// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package http

import (
	"github.com/google/uuid"
	"go-messenger/internal/api/dto"
	"go-messenger/internal/api/errs"
	"go-messenger/internal/models"
	"sync"
)

// serviceMock is a mock implementation of service.
//
//	func TestSomethingThatUsesservice(t *testing.T) {
//
//		// make and configure a mocked service
//		mockedservice := &serviceMock{
//			HandleMessageFunc: func(messageRequest dto.MessageRequest, userConn *UserConn, mapMoqParam *sync.Map)  {
//				panic("mock out the HandleMessage method")
//			},
//			HealthCheckFunc: func() error {
//				panic("mock out the HealthCheck method")
//			},
//			RefreshTokenRevokeFunc: func(uUID uuid.UUID) *errs.HTTPError {
//				panic("mock out the RefreshTokenRevoke method")
//			},
//			RefreshTokenUpdateFunc: func(s string) (string, *errs.HTTPError) {
//				panic("mock out the RefreshTokenUpdate method")
//			},
//			UserCheckFunc: func(userSignIn *dto.UserSignIn) (*models.User, *errs.HTTPError) {
//				panic("mock out the UserCheck method")
//			},
//			UserCreateFunc: func(userSignUp *dto.UserSignUp) (*models.User, error) {
//				panic("mock out the UserCreate method")
//			},
//			UserDeleteFunc: func(s string) error {
//				panic("mock out the UserDelete method")
//			},
//			UserGenerateTokenFunc: func(uUID uuid.UUID) (string, *errs.HTTPError) {
//				panic("mock out the UserGenerateToken method")
//			},
//			UserGetPhoneFunc: func(s string) (*models.User, error) {
//				panic("mock out the UserGetPhone method")
//			},
//			UserUpdateFunc: func(s string, userUpdate *dto.UserUpdate) error {
//				panic("mock out the UserUpdate method")
//			},
//		}
//
//		// use mockedservice in code that requires service
//		// and then make assertions.
//
//	}
type serviceMock struct {
	// HandleMessageFunc mocks the HandleMessage method.
	HandleMessageFunc func(messageRequest dto.MessageRequest, userConn *UserConn, mapMoqParam *sync.Map)

	// HealthCheckFunc mocks the HealthCheck method.
	HealthCheckFunc func() error

	// RefreshTokenRevokeFunc mocks the RefreshTokenRevoke method.
	RefreshTokenRevokeFunc func(uUID uuid.UUID) *errs.HTTPError

	// RefreshTokenUpdateFunc mocks the RefreshTokenUpdate method.
	RefreshTokenUpdateFunc func(s string) (string, *errs.HTTPError)

	// UserCheckFunc mocks the UserCheck method.
	UserCheckFunc func(userSignIn *dto.UserSignIn) (*models.User, *errs.HTTPError)

	// UserCreateFunc mocks the UserCreate method.
	UserCreateFunc func(userSignUp *dto.UserSignUp) (*models.User, error)

	// UserDeleteFunc mocks the UserDelete method.
	UserDeleteFunc func(s string) error

	// UserGenerateTokenFunc mocks the UserGenerateToken method.
	UserGenerateTokenFunc func(uUID uuid.UUID) (string, *errs.HTTPError)

	// UserGetPhoneFunc mocks the UserGetPhone method.
	UserGetPhoneFunc func(s string) (*models.User, error)

	// UserUpdateFunc mocks the UserUpdate method.
	UserUpdateFunc func(s string, userUpdate *dto.UserUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleMessage holds details about calls to the HandleMessage method.
		HandleMessage []struct {
			// MessageRequest is the messageRequest argument value.
			MessageRequest dto.MessageRequest
			// UserConn is the userConn argument value.
			UserConn *UserConn
			// MapMoqParam is the mapMoqParam argument value.
			MapMoqParam *sync.Map
		}
		// HealthCheck holds details about calls to the HealthCheck method.
		HealthCheck []struct {
		}
		// RefreshTokenRevoke holds details about calls to the RefreshTokenRevoke method.
		RefreshTokenRevoke []struct {
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// RefreshTokenUpdate holds details about calls to the RefreshTokenUpdate method.
		RefreshTokenUpdate []struct {
			// S is the s argument value.
			S string
		}
		// UserCheck holds details about calls to the UserCheck method.
		UserCheck []struct {
			// UserSignIn is the userSignIn argument value.
			UserSignIn *dto.UserSignIn
		}
		// UserCreate holds details about calls to the UserCreate method.
		UserCreate []struct {
			// UserSignUp is the userSignUp argument value.
			UserSignUp *dto.UserSignUp
		}
		// UserDelete holds details about calls to the UserDelete method.
		UserDelete []struct {
			// S is the s argument value.
			S string
		}
		// UserGenerateToken holds details about calls to the UserGenerateToken method.
		UserGenerateToken []struct {
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// UserGetPhone holds details about calls to the UserGetPhone method.
		UserGetPhone []struct {
			// S is the s argument value.
			S string
		}
		// UserUpdate holds details about calls to the UserUpdate method.
		UserUpdate []struct {
			// S is the s argument value.
			S string
			// UserUpdate is the userUpdate argument value.
			UserUpdate *dto.UserUpdate
		}
	}
	lockHandleMessage      sync.RWMutex
	lockHealthCheck        sync.RWMutex
	lockRefreshTokenRevoke sync.RWMutex
	lockRefreshTokenUpdate sync.RWMutex
	lockUserCheck          sync.RWMutex
	lockUserCreate         sync.RWMutex
	lockUserDelete         sync.RWMutex
	lockUserGenerateToken  sync.RWMutex
	lockUserGetPhone       sync.RWMutex
	lockUserUpdate         sync.RWMutex
}

// HandleMessage calls HandleMessageFunc.
func (mock *serviceMock) HandleMessage(messageRequest dto.MessageRequest, userConn *UserConn, mapMoqParam *sync.Map) {
	if mock.HandleMessageFunc == nil {
		panic("serviceMock.HandleMessageFunc: method is nil but service.HandleMessage was just called")
	}
	callInfo := struct {
		MessageRequest dto.MessageRequest
		UserConn       *UserConn
		MapMoqParam    *sync.Map
	}{
		MessageRequest: messageRequest,
		UserConn:       userConn,
		MapMoqParam:    mapMoqParam,
	}
	mock.lockHandleMessage.Lock()
	mock.calls.HandleMessage = append(mock.calls.HandleMessage, callInfo)
	mock.lockHandleMessage.Unlock()
	mock.HandleMessageFunc(messageRequest, userConn, mapMoqParam)
}

// HandleMessageCalls gets all the calls that were made to HandleMessage.
// Check the length with:
//
//	len(mockedservice.HandleMessageCalls())
func (mock *serviceMock) HandleMessageCalls() []struct {
	MessageRequest dto.MessageRequest
	UserConn       *UserConn
	MapMoqParam    *sync.Map
} {
	var calls []struct {
		MessageRequest dto.MessageRequest
		UserConn       *UserConn
		MapMoqParam    *sync.Map
	}
	mock.lockHandleMessage.RLock()
	calls = mock.calls.HandleMessage
	mock.lockHandleMessage.RUnlock()
	return calls
}

// HealthCheck calls HealthCheckFunc.
func (mock *serviceMock) HealthCheck() error {
	if mock.HealthCheckFunc == nil {
		panic("serviceMock.HealthCheckFunc: method is nil but service.HealthCheck was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = append(mock.calls.HealthCheck, callInfo)
	mock.lockHealthCheck.Unlock()
	return mock.HealthCheckFunc()
}

// HealthCheckCalls gets all the calls that were made to HealthCheck.
// Check the length with:
//
//	len(mockedservice.HealthCheckCalls())
func (mock *serviceMock) HealthCheckCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHealthCheck.RLock()
	calls = mock.calls.HealthCheck
	mock.lockHealthCheck.RUnlock()
	return calls
}

// RefreshTokenRevoke calls RefreshTokenRevokeFunc.
func (mock *serviceMock) RefreshTokenRevoke(uUID uuid.UUID) *errs.HTTPError {
	if mock.RefreshTokenRevokeFunc == nil {
		panic("serviceMock.RefreshTokenRevokeFunc: method is nil but service.RefreshTokenRevoke was just called")
	}
	callInfo := struct {
		UUID uuid.UUID
	}{
		UUID: uUID,
	}
	mock.lockRefreshTokenRevoke.Lock()
	mock.calls.RefreshTokenRevoke = append(mock.calls.RefreshTokenRevoke, callInfo)
	mock.lockRefreshTokenRevoke.Unlock()
	return mock.RefreshTokenRevokeFunc(uUID)
}

// RefreshTokenRevokeCalls gets all the calls that were made to RefreshTokenRevoke.
// Check the length with:
//
//	len(mockedservice.RefreshTokenRevokeCalls())
func (mock *serviceMock) RefreshTokenRevokeCalls() []struct {
	UUID uuid.UUID
} {
	var calls []struct {
		UUID uuid.UUID
	}
	mock.lockRefreshTokenRevoke.RLock()
	calls = mock.calls.RefreshTokenRevoke
	mock.lockRefreshTokenRevoke.RUnlock()
	return calls
}

// RefreshTokenUpdate calls RefreshTokenUpdateFunc.
func (mock *serviceMock) RefreshTokenUpdate(s string) (string, *errs.HTTPError) {
	if mock.RefreshTokenUpdateFunc == nil {
		panic("serviceMock.RefreshTokenUpdateFunc: method is nil but service.RefreshTokenUpdate was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRefreshTokenUpdate.Lock()
	mock.calls.RefreshTokenUpdate = append(mock.calls.RefreshTokenUpdate, callInfo)
	mock.lockRefreshTokenUpdate.Unlock()
	return mock.RefreshTokenUpdateFunc(s)
}

// RefreshTokenUpdateCalls gets all the calls that were made to RefreshTokenUpdate.
// Check the length with:
//
//	len(mockedservice.RefreshTokenUpdateCalls())
func (mock *serviceMock) RefreshTokenUpdateCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRefreshTokenUpdate.RLock()
	calls = mock.calls.RefreshTokenUpdate
	mock.lockRefreshTokenUpdate.RUnlock()
	return calls
}

// UserCheck calls UserCheckFunc.
func (mock *serviceMock) UserCheck(userSignIn *dto.UserSignIn) (*models.User, *errs.HTTPError) {
	if mock.UserCheckFunc == nil {
		panic("serviceMock.UserCheckFunc: method is nil but service.UserCheck was just called")
	}
	callInfo := struct {
		UserSignIn *dto.UserSignIn
	}{
		UserSignIn: userSignIn,
	}
	mock.lockUserCheck.Lock()
	mock.calls.UserCheck = append(mock.calls.UserCheck, callInfo)
	mock.lockUserCheck.Unlock()
	return mock.UserCheckFunc(userSignIn)
}

// UserCheckCalls gets all the calls that were made to UserCheck.
// Check the length with:
//
//	len(mockedservice.UserCheckCalls())
func (mock *serviceMock) UserCheckCalls() []struct {
	UserSignIn *dto.UserSignIn
} {
	var calls []struct {
		UserSignIn *dto.UserSignIn
	}
	mock.lockUserCheck.RLock()
	calls = mock.calls.UserCheck
	mock.lockUserCheck.RUnlock()
	return calls
}

// UserCreate calls UserCreateFunc.
func (mock *serviceMock) UserCreate(userSignUp *dto.UserSignUp) (*models.User, error) {
	if mock.UserCreateFunc == nil {
		panic("serviceMock.UserCreateFunc: method is nil but service.UserCreate was just called")
	}
	callInfo := struct {
		UserSignUp *dto.UserSignUp
	}{
		UserSignUp: userSignUp,
	}
	mock.lockUserCreate.Lock()
	mock.calls.UserCreate = append(mock.calls.UserCreate, callInfo)
	mock.lockUserCreate.Unlock()
	return mock.UserCreateFunc(userSignUp)
}

// UserCreateCalls gets all the calls that were made to UserCreate.
// Check the length with:
//
//	len(mockedservice.UserCreateCalls())
func (mock *serviceMock) UserCreateCalls() []struct {
	UserSignUp *dto.UserSignUp
} {
	var calls []struct {
		UserSignUp *dto.UserSignUp
	}
	mock.lockUserCreate.RLock()
	calls = mock.calls.UserCreate
	mock.lockUserCreate.RUnlock()
	return calls
}

// UserDelete calls UserDeleteFunc.
func (mock *serviceMock) UserDelete(s string) error {
	if mock.UserDeleteFunc == nil {
		panic("serviceMock.UserDeleteFunc: method is nil but service.UserDelete was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockUserDelete.Lock()
	mock.calls.UserDelete = append(mock.calls.UserDelete, callInfo)
	mock.lockUserDelete.Unlock()
	return mock.UserDeleteFunc(s)
}

// UserDeleteCalls gets all the calls that were made to UserDelete.
// Check the length with:
//
//	len(mockedservice.UserDeleteCalls())
func (mock *serviceMock) UserDeleteCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockUserDelete.RLock()
	calls = mock.calls.UserDelete
	mock.lockUserDelete.RUnlock()
	return calls
}

// UserGenerateToken calls UserGenerateTokenFunc.
func (mock *serviceMock) UserGenerateToken(uUID uuid.UUID) (string, *errs.HTTPError) {
	if mock.UserGenerateTokenFunc == nil {
		panic("serviceMock.UserGenerateTokenFunc: method is nil but service.UserGenerateToken was just called")
	}
	callInfo := struct {
		UUID uuid.UUID
	}{
		UUID: uUID,
	}
	mock.lockUserGenerateToken.Lock()
	mock.calls.UserGenerateToken = append(mock.calls.UserGenerateToken, callInfo)
	mock.lockUserGenerateToken.Unlock()
	return mock.UserGenerateTokenFunc(uUID)
}

// UserGenerateTokenCalls gets all the calls that were made to UserGenerateToken.
// Check the length with:
//
//	len(mockedservice.UserGenerateTokenCalls())
func (mock *serviceMock) UserGenerateTokenCalls() []struct {
	UUID uuid.UUID
} {
	var calls []struct {
		UUID uuid.UUID
	}
	mock.lockUserGenerateToken.RLock()
	calls = mock.calls.UserGenerateToken
	mock.lockUserGenerateToken.RUnlock()
	return calls
}

// UserGetPhone calls UserGetPhoneFunc.
func (mock *serviceMock) UserGetPhone(s string) (*models.User, error) {
	if mock.UserGetPhoneFunc == nil {
		panic("serviceMock.UserGetPhoneFunc: method is nil but service.UserGetPhone was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockUserGetPhone.Lock()
	mock.calls.UserGetPhone = append(mock.calls.UserGetPhone, callInfo)
	mock.lockUserGetPhone.Unlock()
	return mock.UserGetPhoneFunc(s)
}

// UserGetPhoneCalls gets all the calls that were made to UserGetPhone.
// Check the length with:
//
//	len(mockedservice.UserGetPhoneCalls())
func (mock *serviceMock) UserGetPhoneCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockUserGetPhone.RLock()
	calls = mock.calls.UserGetPhone
	mock.lockUserGetPhone.RUnlock()
	return calls
}

// UserUpdate calls UserUpdateFunc.
func (mock *serviceMock) UserUpdate(s string, userUpdate *dto.UserUpdate) error {
	if mock.UserUpdateFunc == nil {
		panic("serviceMock.UserUpdateFunc: method is nil but service.UserUpdate was just called")
	}
	callInfo := struct {
		S          string
		UserUpdate *dto.UserUpdate
	}{
		S:          s,
		UserUpdate: userUpdate,
	}
	mock.lockUserUpdate.Lock()
	mock.calls.UserUpdate = append(mock.calls.UserUpdate, callInfo)
	mock.lockUserUpdate.Unlock()
	return mock.UserUpdateFunc(s, userUpdate)
}

// UserUpdateCalls gets all the calls that were made to UserUpdate.
// Check the length with:
//
//	len(mockedservice.UserUpdateCalls())
func (mock *serviceMock) UserUpdateCalls() []struct {
	S          string
	UserUpdate *dto.UserUpdate
} {
	var calls []struct {
		S          string
		UserUpdate *dto.UserUpdate
	}
	mock.lockUserUpdate.RLock()
	calls = mock.calls.UserUpdate
	mock.lockUserUpdate.RUnlock()
	return calls
}
