// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"github.com/google/uuid"
	"go-messenger/internal/api/dto"
	"go-messenger/internal/models"
	"sync"
)

// storageMock is a mock implementation of storage.
//
//	func TestSomethingThatUsesstorage(t *testing.T) {
//
//		// make and configure a mocked storage
//		mockedstorage := &storageMock{
//			PingFunc: func() error {
//				panic("mock out the Ping method")
//			},
//			RefreshTokenGetFunc: func(s string) (*models.RefreshToken, error) {
//				panic("mock out the RefreshTokenGet method")
//			},
//			RefreshTokenRevokeFunc: func(s string) error {
//				panic("mock out the RefreshTokenRevoke method")
//			},
//			RefreshTokenSaveFunc: func(refreshToken *models.RefreshToken) error {
//				panic("mock out the RefreshTokenSave method")
//			},
//			UserDeleteFunc: func(s string) error {
//				panic("mock out the UserDelete method")
//			},
//			UserGetIDFunc: func(uUID uuid.UUID) (*models.User, error) {
//				panic("mock out the UserGetID method")
//			},
//			UserGetPhoneFunc: func(s string) (*models.User, error) {
//				panic("mock out the UserGetPhone method")
//			},
//			UserInsertFunc: func(user *models.User) error {
//				panic("mock out the UserInsert method")
//			},
//			UserUpdateFunc: func(s string, userUpdate *dto.UserUpdate) error {
//				panic("mock out the UserUpdate method")
//			},
//		}
//
//		// use mockedstorage in code that requires storage
//		// and then make assertions.
//
//	}
type storageMock struct {
	// PingFunc mocks the Ping method.
	PingFunc func() error

	// RefreshTokenGetFunc mocks the RefreshTokenGet method.
	RefreshTokenGetFunc func(s string) (*models.RefreshToken, error)

	// RefreshTokenRevokeFunc mocks the RefreshTokenRevoke method.
	RefreshTokenRevokeFunc func(s string) error

	// RefreshTokenSaveFunc mocks the RefreshTokenSave method.
	RefreshTokenSaveFunc func(refreshToken *models.RefreshToken) error

	// UserDeleteFunc mocks the UserDelete method.
	UserDeleteFunc func(s string) error

	// UserGetIDFunc mocks the UserGetID method.
	UserGetIDFunc func(uUID uuid.UUID) (*models.User, error)

	// UserGetPhoneFunc mocks the UserGetPhone method.
	UserGetPhoneFunc func(s string) (*models.User, error)

	// UserInsertFunc mocks the UserInsert method.
	UserInsertFunc func(user *models.User) error

	// UserUpdateFunc mocks the UserUpdate method.
	UserUpdateFunc func(s string, userUpdate *dto.UserUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// Ping holds details about calls to the Ping method.
		Ping []struct {
		}
		// RefreshTokenGet holds details about calls to the RefreshTokenGet method.
		RefreshTokenGet []struct {
			// S is the s argument value.
			S string
		}
		// RefreshTokenRevoke holds details about calls to the RefreshTokenRevoke method.
		RefreshTokenRevoke []struct {
			// S is the s argument value.
			S string
		}
		// RefreshTokenSave holds details about calls to the RefreshTokenSave method.
		RefreshTokenSave []struct {
			// RefreshToken is the refreshToken argument value.
			RefreshToken *models.RefreshToken
		}
		// UserDelete holds details about calls to the UserDelete method.
		UserDelete []struct {
			// S is the s argument value.
			S string
		}
		// UserGetID holds details about calls to the UserGetID method.
		UserGetID []struct {
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// UserGetPhone holds details about calls to the UserGetPhone method.
		UserGetPhone []struct {
			// S is the s argument value.
			S string
		}
		// UserInsert holds details about calls to the UserInsert method.
		UserInsert []struct {
			// User is the user argument value.
			User *models.User
		}
		// UserUpdate holds details about calls to the UserUpdate method.
		UserUpdate []struct {
			// S is the s argument value.
			S string
			// UserUpdate is the userUpdate argument value.
			UserUpdate *dto.UserUpdate
		}
	}
	lockPing               sync.RWMutex
	lockRefreshTokenGet    sync.RWMutex
	lockRefreshTokenRevoke sync.RWMutex
	lockRefreshTokenSave   sync.RWMutex
	lockUserDelete         sync.RWMutex
	lockUserGetID          sync.RWMutex
	lockUserGetPhone       sync.RWMutex
	lockUserInsert         sync.RWMutex
	lockUserUpdate         sync.RWMutex
}

// Ping calls PingFunc.
func (mock *storageMock) Ping() error {
	if mock.PingFunc == nil {
		panic("storageMock.PingFunc: method is nil but storage.Ping was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc()
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedstorage.PingCalls())
func (mock *storageMock) PingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// RefreshTokenGet calls RefreshTokenGetFunc.
func (mock *storageMock) RefreshTokenGet(s string) (*models.RefreshToken, error) {
	if mock.RefreshTokenGetFunc == nil {
		panic("storageMock.RefreshTokenGetFunc: method is nil but storage.RefreshTokenGet was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRefreshTokenGet.Lock()
	mock.calls.RefreshTokenGet = append(mock.calls.RefreshTokenGet, callInfo)
	mock.lockRefreshTokenGet.Unlock()
	return mock.RefreshTokenGetFunc(s)
}

// RefreshTokenGetCalls gets all the calls that were made to RefreshTokenGet.
// Check the length with:
//
//	len(mockedstorage.RefreshTokenGetCalls())
func (mock *storageMock) RefreshTokenGetCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRefreshTokenGet.RLock()
	calls = mock.calls.RefreshTokenGet
	mock.lockRefreshTokenGet.RUnlock()
	return calls
}

// RefreshTokenRevoke calls RefreshTokenRevokeFunc.
func (mock *storageMock) RefreshTokenRevoke(s string) error {
	if mock.RefreshTokenRevokeFunc == nil {
		panic("storageMock.RefreshTokenRevokeFunc: method is nil but storage.RefreshTokenRevoke was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRefreshTokenRevoke.Lock()
	mock.calls.RefreshTokenRevoke = append(mock.calls.RefreshTokenRevoke, callInfo)
	mock.lockRefreshTokenRevoke.Unlock()
	return mock.RefreshTokenRevokeFunc(s)
}

// RefreshTokenRevokeCalls gets all the calls that were made to RefreshTokenRevoke.
// Check the length with:
//
//	len(mockedstorage.RefreshTokenRevokeCalls())
func (mock *storageMock) RefreshTokenRevokeCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRefreshTokenRevoke.RLock()
	calls = mock.calls.RefreshTokenRevoke
	mock.lockRefreshTokenRevoke.RUnlock()
	return calls
}

// RefreshTokenSave calls RefreshTokenSaveFunc.
func (mock *storageMock) RefreshTokenSave(refreshToken *models.RefreshToken) error {
	if mock.RefreshTokenSaveFunc == nil {
		panic("storageMock.RefreshTokenSaveFunc: method is nil but storage.RefreshTokenSave was just called")
	}
	callInfo := struct {
		RefreshToken *models.RefreshToken
	}{
		RefreshToken: refreshToken,
	}
	mock.lockRefreshTokenSave.Lock()
	mock.calls.RefreshTokenSave = append(mock.calls.RefreshTokenSave, callInfo)
	mock.lockRefreshTokenSave.Unlock()
	return mock.RefreshTokenSaveFunc(refreshToken)
}

// RefreshTokenSaveCalls gets all the calls that were made to RefreshTokenSave.
// Check the length with:
//
//	len(mockedstorage.RefreshTokenSaveCalls())
func (mock *storageMock) RefreshTokenSaveCalls() []struct {
	RefreshToken *models.RefreshToken
} {
	var calls []struct {
		RefreshToken *models.RefreshToken
	}
	mock.lockRefreshTokenSave.RLock()
	calls = mock.calls.RefreshTokenSave
	mock.lockRefreshTokenSave.RUnlock()
	return calls
}

// UserDelete calls UserDeleteFunc.
func (mock *storageMock) UserDelete(s string) error {
	if mock.UserDeleteFunc == nil {
		panic("storageMock.UserDeleteFunc: method is nil but storage.UserDelete was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockUserDelete.Lock()
	mock.calls.UserDelete = append(mock.calls.UserDelete, callInfo)
	mock.lockUserDelete.Unlock()
	return mock.UserDeleteFunc(s)
}

// UserDeleteCalls gets all the calls that were made to UserDelete.
// Check the length with:
//
//	len(mockedstorage.UserDeleteCalls())
func (mock *storageMock) UserDeleteCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockUserDelete.RLock()
	calls = mock.calls.UserDelete
	mock.lockUserDelete.RUnlock()
	return calls
}

// UserGetID calls UserGetIDFunc.
func (mock *storageMock) UserGetID(uUID uuid.UUID) (*models.User, error) {
	if mock.UserGetIDFunc == nil {
		panic("storageMock.UserGetIDFunc: method is nil but storage.UserGetID was just called")
	}
	callInfo := struct {
		UUID uuid.UUID
	}{
		UUID: uUID,
	}
	mock.lockUserGetID.Lock()
	mock.calls.UserGetID = append(mock.calls.UserGetID, callInfo)
	mock.lockUserGetID.Unlock()
	return mock.UserGetIDFunc(uUID)
}

// UserGetIDCalls gets all the calls that were made to UserGetID.
// Check the length with:
//
//	len(mockedstorage.UserGetIDCalls())
func (mock *storageMock) UserGetIDCalls() []struct {
	UUID uuid.UUID
} {
	var calls []struct {
		UUID uuid.UUID
	}
	mock.lockUserGetID.RLock()
	calls = mock.calls.UserGetID
	mock.lockUserGetID.RUnlock()
	return calls
}

// UserGetPhone calls UserGetPhoneFunc.
func (mock *storageMock) UserGetPhone(s string) (*models.User, error) {
	if mock.UserGetPhoneFunc == nil {
		panic("storageMock.UserGetPhoneFunc: method is nil but storage.UserGetPhone was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockUserGetPhone.Lock()
	mock.calls.UserGetPhone = append(mock.calls.UserGetPhone, callInfo)
	mock.lockUserGetPhone.Unlock()
	return mock.UserGetPhoneFunc(s)
}

// UserGetPhoneCalls gets all the calls that were made to UserGetPhone.
// Check the length with:
//
//	len(mockedstorage.UserGetPhoneCalls())
func (mock *storageMock) UserGetPhoneCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockUserGetPhone.RLock()
	calls = mock.calls.UserGetPhone
	mock.lockUserGetPhone.RUnlock()
	return calls
}

// UserInsert calls UserInsertFunc.
func (mock *storageMock) UserInsert(user *models.User) error {
	if mock.UserInsertFunc == nil {
		panic("storageMock.UserInsertFunc: method is nil but storage.UserInsert was just called")
	}
	callInfo := struct {
		User *models.User
	}{
		User: user,
	}
	mock.lockUserInsert.Lock()
	mock.calls.UserInsert = append(mock.calls.UserInsert, callInfo)
	mock.lockUserInsert.Unlock()
	return mock.UserInsertFunc(user)
}

// UserInsertCalls gets all the calls that were made to UserInsert.
// Check the length with:
//
//	len(mockedstorage.UserInsertCalls())
func (mock *storageMock) UserInsertCalls() []struct {
	User *models.User
} {
	var calls []struct {
		User *models.User
	}
	mock.lockUserInsert.RLock()
	calls = mock.calls.UserInsert
	mock.lockUserInsert.RUnlock()
	return calls
}

// UserUpdate calls UserUpdateFunc.
func (mock *storageMock) UserUpdate(s string, userUpdate *dto.UserUpdate) error {
	if mock.UserUpdateFunc == nil {
		panic("storageMock.UserUpdateFunc: method is nil but storage.UserUpdate was just called")
	}
	callInfo := struct {
		S          string
		UserUpdate *dto.UserUpdate
	}{
		S:          s,
		UserUpdate: userUpdate,
	}
	mock.lockUserUpdate.Lock()
	mock.calls.UserUpdate = append(mock.calls.UserUpdate, callInfo)
	mock.lockUserUpdate.Unlock()
	return mock.UserUpdateFunc(s, userUpdate)
}

// UserUpdateCalls gets all the calls that were made to UserUpdate.
// Check the length with:
//
//	len(mockedstorage.UserUpdateCalls())
func (mock *storageMock) UserUpdateCalls() []struct {
	S          string
	UserUpdate *dto.UserUpdate
} {
	var calls []struct {
		S          string
		UserUpdate *dto.UserUpdate
	}
	mock.lockUserUpdate.RLock()
	calls = mock.calls.UserUpdate
	mock.lockUserUpdate.RUnlock()
	return calls
}
