// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

import (
 _ "github.com/golangci/golangci-lint/cmd/golangci-lint"
 _ "github.com/matryer/moq"
)

//go:generate go install github.com/golangci/golangci-lint/cmd/golangci-lint
//go:generate go install github.com/matryer/moq